apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootrestapi
  labels:
    app: springbootrestapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootrestapi
  template:
    metadata:
      labels:
        app: springbootrestapi
    spec:
      containers:
      - name: springbootrestapi
        image: webapi4qrcode.azurecr.io/springbootrestapi:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springbootrestapi
spec:
  selector:
    app: springbootrestapi
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
